### ISSUE TITLE
Better alerts before the disaster. 

### ISSUE THREAD

**Issue by Lindavzisme** [CrowdRescueHQ/CrowdRescue#61]
per Meghan UX

Like we did to get the zello info out before Maria

https://crowdrescuehq.slack.com/archives/C77M927UL/p1507588331000091?thread_ts=1507578972.000312&cid=C77M927UL

**Comment by izwick-schachter** [comment]
For people who don't remember or weren't here, can you clarify what we did to get the zello info out for Maria? If I recall correctly, we tweeted it out, which is totally unrelated to SCOT. I don't think SCOT has any role in pre-disaster prep. Because I think it's outside SCOT's scope, I'm closing this issue. If you can point out a thing SCOT should be doing pre-disaster, add it here and I'll reopen it.

**Comment by Lindavzisme** [comment]
We have not defined the scope of SCOT. Until we do, I would like to keep it open.
